#!/usr/bin/env ruby
# frozen_string_literal: true

$LOAD_PATH.unshift(File.expand_path("../lib", __dir__))

require "optparse"

options = {}

OptionParser.new do |parser|
  parser.on("--version", "Print the gem's version") do
    require "rubydex/version"
    puts "v#{Rubydex::VERSION}"
    exit
  end

  parser.on("-h", "--help", "Prints this help") do
    puts parser
    exit
  end

  parser.on("-i", "--interactive", "Open an interactive session with a populated graph for the current workspace") do
    options[:interactive] = true
  end
end.parse!

require "rubydex"

def __with_timer(message, &block)
  print(message)
  start = Process.clock_gettime(Process::CLOCK_MONOTONIC, :float_millisecond)
  block.call
  duration = Process.clock_gettime(Process::CLOCK_MONOTONIC, :float_millisecond) - start
  puts " finished in #{duration.round(2)}ms"
end

graph = Rubydex::Graph.new
graph.load_config

__with_timer("Indexing workspace...") { graph.index_workspace }
__with_timer("Resolving graph...") { graph.resolve }

if options[:interactive]
  begin
    require "irb"
    IRB.setup(nil)
    IRB.conf[:IRB_NAME] = "rubydex"
    workspace = IRB::WorkSpace.new(binding)
    IRB::Irb.new(workspace).run(IRB.conf)
  rescue LoadError
    abort("Interactive mode requires `irb` to be in the bundle")
  end
end
