name: Index top 100 gems

on: [push, pull_request]

jobs:
  indexing_top_gems:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Install Rust tools
        run: |
          rustup update --no-self-update stable
          rustup default stable
          rustup component add --toolchain stable clippy rustfmt

      - name: Set up Ruby
        uses: ruby/setup-ruby@d45b1a4e94b71acab930e56e79c6aa188764e7f9 # v1.316.0
        with:
          bundler-cache: true

      - name: Restore Rust compile cache
        id: rust-compile-cache-restore
        uses: actions/cache/restore@v6
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-rust

      - name: Run Ruby tests
        env:
          RUST_BACKTRACE: full
        run: bundle exec rake index_top_gems

      - name: Save Rust compile cache
        id: rust-compile-cache-save
        uses: actions/cache/save@v6
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ steps.rust-compile-cache-restore.outputs.cache-primary-key }}
