name: Memleak

on:
  push:
    paths:
      - ".github/workflows/memleak.yml"
      - "rust/**"
      - "ext/**"
  pull_request:
    paths:
      - ".github/workflows/memleak.yml"
      - "rust/**"
      - "ext/**"

jobs:
  memleak:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        sanitizer: [memory, leak, thread]
    name: memleak (${{ matrix.sanitizer }})
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3

      - name: Set up Ruby
        uses: ruby/setup-ruby@afeafc3d1ab54a631816aba4c914a0081c12ff2f # v1.310.0
        with:
          bundler-cache: true

      - run: sudo apt-get update && sudo apt-get install -y valgrind

      - name: Install Rust tools
        run: |
          rustup update --no-self-update stable
          rustup default stable
          rustup component add rust-src --toolchain nightly-x86_64-unknown-linux-gnu

      - name: Run tests capturing leaks with `${{ matrix.sanitizer }}` sanitizer
        run: SANITIZER=${{ matrix.sanitizer }} bundle exec rake ruby_test:valgrind
